2021-02-26 07:34:15.501 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "min"\nLINE 1: min(t7.cprz1) as Min_CPR_z1, max(t7.cprz1) as MAX_CPR_Z1, mi...\n        ^\n'}
2021-02-26 07:35:33.333 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "min"\nLINE 1: min(t7.cprz1) as Min_CPR_z1, max(t7.cprz1) as MAX_CPR_Z1,\n        ^\n'}
2021-02-26 07:37:14.380 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "min"\nLINE 1: min(t7.cprz1) as MINCPR_z1, max(t7.cprz1) as MAXCPR_Z1,\n        ^\n'}
2021-02-26 07:41:03.750 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "min"\nLINE 1: min(t7.cprz1) as MINCPR_z1, max(t7.cprz1) as MAXCPR_Z1,\n        ^\n'}
2021-02-26 07:44:41.149 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "min"\nLINE 1: min(t7.cprz1) as MINCPR_z1, max(t7.cprz1) as MAXCPR_Z1,\n        ^\n'}
2021-03-02 07:14:39.036 ERROR response_module.py response_module - response_exception:{'message': 'column "none" does not exist\nLINE 7: ...pm.param_name =\'None\' and zd.zone_name=\'None\' and run=None))\n                                                                 ^\n'}
2021-03-02 07:54:25.778 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 07:57:37.280 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 07:57:40.243 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 08:02:34.030 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 08:02:35.774 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 08:02:55.236 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 08:04:24.321 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 08:04:27.117 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 08:04:54.539 ERROR response_module.py response_module - response_exception:{'message': 'column reference "uom" is ambiguous\nLINE 1: ...un\',run,\'run_hours\',run_hours,\'pro_val\',pro_val, \'uom\',uom))\n                                                                  ^\n'}
2021-03-02 08:13:14.287 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "from"\nLINE 2: from process_tags pt\n        ^\n'}
2021-03-02 08:14:28.422 ERROR response_module.py response_module - response_exception:{'message': 'column "none" does not exist\nLINE 7: ...pm.param_name =\'None\' and zd.zone_name=\'None\' and run=None))\n                                                                 ^\n'}
2021-03-02 08:14:58.134 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "from"\nLINE 2: from process_tags pt\n        ^\n'}
2021-03-02 08:15:42.745 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "from"\nLINE 2: from process_tags pt\n        ^\n'}
2021-03-02 08:15:45.743 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "from"\nLINE 2: from process_tags pt\n        ^\n'}
2021-03-02 08:17:46.484 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "from"\nLINE 2: from process_tags pt\n        ^\n'}
2021-03-02 08:21:30.452 ERROR response_module.py response_module - response_exception:{'message': 'argument list must have even number of elements\nHINT:  The arguments of json_build_object() must consist of alternating keys and values.\n'}
2021-03-02 10:25:38.214 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "\'Fuel Gas Flow  (Floor)\'"\nLINE 8: where pm.param_name in\'Fuel Gas Flow  (Floor)\' and zd.zone_n...\n                              ^\n'}
2021-03-02 10:27:38.325 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "\'Fuel Gas Flow  (Floor)\'"\nLINE 8: where pm.param_name in \'Fuel Gas Flow  (Floor)\' and zd.zone_...\n                               ^\n'}
2021-03-02 10:31:02.371 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "\'Fuel Gas Flow  (Floor)\'"\nLINE 8: where pm.param_name in \'Fuel Gas Flow  (Floor)\' and zd.zone_...\n                               ^\n'}
2021-03-02 10:32:42.047 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "\'parameter_tag\'"\nLINE 8: where pm.param_name in \'parameter_tag\' and zd.zone_name=\'Zon...\n                               ^\n'}
2021-03-02 10:34:05.092 ERROR response_module.py response_module - response_exception:{'message': 'column "none" does not exist\nLINE 8: ...m.param_name = \'None\' and zd.zone_name=\'None\' and run=None))\n                                                                 ^\n'}
2021-03-02 10:57:49.895 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "where"\nLINE 13: where pm.param_name = \'Fuel Gas Flow  (Floor)\' and zd.zone_n...\n         ^\n'}
2021-03-02 10:59:48.205 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at end of input\nLINE 12: tm.param_key =8 and zd.zone_key =1 and run=1\n                                                     ^\n'}
2021-03-02 11:00:10.675 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at end of input\nLINE 12: tm.param_key =8 and zd.zone_key =1 and run=1)\n                                                      ^\n'}
2021-03-22 10:48:32.978 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "select"\nLINE 4: (select obs_time, tmtz1, tmtz2, tmtz3 from raw_data limit 1)...\n         ^\n'}
2021-03-22 10:48:59.872 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "#"\nLINE 2: # SELECT json_build_object(\'SOR\', (SELECT json_agg(json_buil...\n        ^\n'}
2021-03-22 11:12:28.869 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "where"\nLINE 4: where pm.param_name = \'{parameter_tag}\' and zd.zone_name=\'{Z...\n        ^\n'}
2021-03-22 11:13:22.831 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "select"\nLINE 3: (select obs_time ,tmtz1 ,tmtz2, tmtz3, cprz1, cprz2, cprz3  ...\n         ^\n'}
2021-03-22 11:14:20.817 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "("\nLINE 2: (select obs_time ,tmtz1 ,tmtz2, tmtz3, cprz1, cprz2, cprz3  ...\n        ^\n'}
2021-03-22 11:14:45.751 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near "("\nLINE 2: (select obs_time ,tmtz1 ,tmtz2, tmtz3, cprz1, cprz2, cprz3  ...\n        ^\n'}
2021-03-22 11:21:48.792 ERROR response_module.py response_module - response_exception:{'message': 'column "none" does not exist\nLINE 8: ...m.param_name = \'None\' and zd.zone_name=\'None\' and run=None))\n                                                                 ^\n'}
2021-03-22 12:41:58.936 ERROR response_module.py response_module - response_exception:{'message': 'column "none" does not exist\nLINE 1: ...,\'cprz2\',cprz2,\'cprz3\',cprz2))from raw_data where run=None))\n                                                                 ^\n'}
2021-03-22 12:43:34.920 ERROR response_module.py response_module - response_exception:{'message': 'list indices must be integers or slices, not str'}
2021-03-22 12:43:54.766 ERROR response_module.py response_module - response_exception:{'message': 'list indices must be integers or slices, not str'}
2021-03-22 12:43:57.475 ERROR response_module.py response_module - response_exception:{'message': 'list indices must be integers or slices, not str'}
2021-03-22 12:44:48.073 ERROR response_module.py response_module - response_exception:{'message': 'list indices must be integers or slices, not str'}
2021-03-22 12:49:31.557 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near ")"\nLINE 3: , \'efrz1\', efrz1, \'efrz2\', efrz2, \'efrz3\', efrz3,))from raw_...\n                                                         ^\n'}
2021-03-22 12:51:27.613 ERROR response_module.py response_module - response_exception:{'message': 'type "shcrz2" does not exist\nLINE 3: ...efrz2, \'efrz3\', efrz3, \'shcrz1\', shcrz1,\'shcrz2\', shcrz2\' sh...\n                                                             ^\n'}
2021-03-22 12:51:31.614 ERROR response_module.py response_module - response_exception:{'message': 'type "shcrz2" does not exist\nLINE 3: ...efrz2, \'efrz3\', efrz3, \'shcrz1\', shcrz1,\'shcrz2\', shcrz2\' sh...\n                                                             ^\n'}
2021-03-22 12:51:59.449 ERROR response_module.py response_module - response_exception:{'message': 'type "shcrz2" does not exist\nLINE 3: ...efrz2, \'efrz3\', efrz3, \'shcrz1\', shcrz1,\'shcrz2\', shcrz2\' sh...\n                                                             ^\n'}
2021-03-22 12:57:20.649 ERROR response_module.py response_module - response_exception:{'message': 'syntax error at or near ")"\nLINE 5: ))from raw_data where run=2))\n        ^\n'}
